import { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

export const translations = {
  en: {
    dashboard: 'Dashboard',
    pos: 'Point of Sale',
    products: 'Products',
    categories: 'Categories',
    staff: 'Staff',
    orders: 'Orders',
    signOut: 'Sign Out',
    systemOnline: 'System Online',
    revenueToday: 'Revenue Today',
    ordersToday: 'Orders Today',
    totalProducts: 'Total Products',
    totalStaff: 'Total Staff',
    revenueOverview: 'Revenue Overview',
    last6Months: 'Last 6 months',
    bestSelling: 'Best Selling',
    topProducts: 'Top products',
    recentOrders: 'Recent Orders',
    latestTransactions: 'Latest transactions',
    orderId: 'Order ID',
    cashier: 'Cashier',
    total: 'Total',
    payment: 'Payment',
    status: 'Status',
    loading: 'Loading...',
    cashPayments: 'cash payments',
    transactions: 'transactions',
    inInventory: 'in inventory',
    activeUsers: 'active users',
    sold: 'sold',
    addProduct: '+ Add Product',
    editProduct: 'Edit Product',
    addCategory: '+ Add Category',
    editCategory: 'Edit Category',
    addStaff: '+ Add Staff',
    editStaff: 'Edit Staff',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search...',
    name: 'Name',
    price: 'Price',
    stock: 'Stock',
    category: 'Category',
    role: 'Role',
    email: 'Email',
    password: 'Password',
    all: 'All',
    cart: 'Cart',
    cartEmpty: 'Cart is empty',
    subtotal: 'Subtotal',
    discount: 'Discount',
    cash: 'Pay Cash',
    khqr: 'Pay KHQR',
    clearCart: 'Clear Cart',
    change: 'Change',
    noOrders: 'No orders',
    noProducts: 'No products',
    noCategories: 'No categories',
    noStaff: 'No staff',
    confirmDelete: 'Delete this item?',
    manageProducts: 'Manage all products',
    manageCategories: 'Manage all categories',
    manageStaff: 'Manage all staff',
    allOrders: 'All orders',
    selectOrder: 'Select an order to view details',
    revenue: 'Revenue',
    totalOrders: 'Total',
    items: 'Items',
    date: 'Date',
    selectCategory: '-- Select Category --',
    barcode: 'Barcode',
    optional: 'optional',
    image: 'Image',
    description: 'Description',
    cashiers: 'Cashiers',
    admins: 'Admins',
    createdAt: 'Created',
  },
  km: {
    dashboard: 'ផ្ទាំងគ្រប់គ្រង',
    pos: 'ប្រព័ន្ធលក់',
    products: 'ផលិតផល',
    categories: 'ប្រភេទ',
    staff: 'បុគ្គលិក',
    orders: 'បញ្ជាទិញ',
    signOut: 'ចាកចេញ',
    systemOnline: 'ប្រព័ន្ធដំណើរការ',
    revenueToday: 'ចំណូលថ្ងៃនេះ',
    ordersToday: 'Orders ថ្ងៃនេះ',
    totalProducts: 'ផលិតផលទាំងអស់',
    totalStaff: 'បុគ្គលិកទាំងអស់',
    revenueOverview: 'ទិដ្ឋភាពចំណូល',
    last6Months: '6 ខែចុងក្រោយ',
    bestSelling: 'លក់ដាច់បំផុត',
    topProducts: 'ផលិតផលកំពូល',
    recentOrders: 'Orders ថ្មីៗ',
    latestTransactions: 'ប្រតិបត្តិការចុងក្រោយ',
    orderId: 'លេខ Order',
    cashier: 'អ្នកគិតលុយ',
    total: 'សរុប',
    payment: 'ការបង់',
    status: 'ស្ថានភាព',
    loading: 'កំពុងផ្ទុក...',
    cashPayments: 'ការបង់សាច់ប្រាក់',
    transactions: 'ប្រតិបត្តិការ',
    inInventory: 'នៅក្នុងស្តុក',
    activeUsers: 'អ្នកប្រើសកម្ម',
    sold: 'បានលក់',
    addProduct: '+ បន្ថែមផលិតផល',
    editProduct: 'កែផលិតផល',
    addCategory: '+ បន្ថែមប្រភេទ',
    editCategory: 'កែប្រភេទ',
    addStaff: '+ បន្ថែមបុគ្គលិក',
    editStaff: 'កែបុគ្គលិក',
    save: 'រក្សាទុក',
    cancel: 'បោះបង់',
    delete: 'លុប',
    edit: 'កែ',
    search: 'ស្វែងរក...',
    name: 'ឈ្មោះ',
    price: 'តម្លៃ',
    stock: 'ស្តុក',
    category: 'ប្រភេទ',
    role: 'តួនាទី',
    email: 'អ៊ីមែល',
    password: 'លេខសម្ងាត់',
    all: 'ទាំងអស់',
    cart: 'កន្ត្រក',
    cartEmpty: 'កន្ត្រកទទេ',
    subtotal: 'សរុបរង',
    discount: 'បញ្ចុះតម្លៃ',
    cash: 'បង់សាច់ប្រាក់',
    khqr: 'បង់ KHQR',
    clearCart: 'លុបកន្ត្រក',
    change: 'អាប់',
    noOrders: 'គ្មាន order',
    noProducts: 'គ្មានផលិតផល',
    noCategories: 'គ្មានប្រភេទ',
    noStaff: 'គ្មានបុគ្គលិក',
    confirmDelete: 'លុបទិន្នន័យនេះ?',
    manageProducts: 'គ្រប់គ្រងផលិតផលទាំងអស់',
    manageCategories: 'គ្រប់គ្រងប្រភេទទាំងអស់',
    manageStaff: 'គ្រប់គ្រងបុគ្គលិកទាំងអស់',
    allOrders: 'Orders ទាំងអស់',
    selectOrder: 'ជ្រើស order ដើម្បីមើលព័ត៌មាន',
    revenue: 'ចំណូល',
    totalOrders: 'សរុប',
    items: 'ទំនិញ',
    date: 'ថ្ងៃ',
    selectCategory: '-- ជ្រើសប្រភេទ --',
    barcode: 'បាកូដ',
    optional: 'មិនចាំបាច់',
    image: 'រូបភាព',
    description: 'ការពិពណ៌នា',
    cashiers: 'អ្នកគិតលុយ',
    admins: 'អ្នកគ្រប់គ្រង',
    createdAt: 'បង្កើតនៅ',
  }
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(localStorage.getItem('lang') || 'en')

  // ← បន្ថែម useEffect នេះ
  useEffect(() => {
    document.body.style.fontFamily = lang === 'km'
      ? "'Hanuman', 'Inter', sans-serif"
      : "'Inter', sans-serif"
  }, [lang])

  const toggleLang = () => {
    const newLang = lang === 'en' ? 'km' : 'en'
    setLang(newLang)
    localStorage.setItem('lang', newLang)
  }

  const t = (key) => translations[lang][key] || key

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLang = () => useContext(LanguageContext)